%% Probabilistic tractography  between the two ROIs, document the process
close all; clear all;
% Create subject list
basedir   = '/share/kalanit/biac2/kgs/projects/NFA_tasks/data_mrAuto';
cd(basedir)
subjects  = dir('*dti_mrTrix3*');

% subjects  = subjects([1:3,5:21]);
% subjects  = subjects([5]);
hemis     = {'lh'};  % For now we don't do rh
lmaxs     = {'8'};  % For now we just check 12
roi1s     = {'IFG_union_morphing_reading_vs_all_projed_gmwmi.nii.gz',...
             'IPCS_morphing_adding_vs_all_projed_gmwmi.nii.gz',...
             'IFG_union_morphing_reading_vs_all_projed_gmwmi.nii.gz',...
             'IPCS_morphing_adding_vs_all_projed_gmwmi.nii.gz', ...
             'IFG_union_morphing_reading_vs_all_projed_gmwmi.nii.gz',...
             'IPCS_morphing_adding_vs_all_projed_gmwmi.nii.gz'};
roi2s     = {'pSTS_MTG_union_morphing_reading_vs_all_projed_gmwmi.nii.gz', ...
             'ITG_morphing_adding_projed_gmwmi.nii.gz',...
             'ISMG_morphing_reading_vs_all_projed_gmwmi.nii.gz',...
             'ISMG_morphing_adding_vs_all_projed_gmwmi.nii.gz', ...
             'ITG_intersection_math_reading_projed_gmwmi.nii.gz', ...
             'ITG_intersection_math_reading_projed_gmwmi.nii.gz'};
    tractNames= {'IFG2STS', ...
                 'IPCS2ITG', ...
                 'IFG2ISMGread', ...
                 'IPCS2ISMGmath', ...
                 'IFG2inters', ...
                 'IPCS2inters'};       
         
for ns=1:length(subjects)
    fwDir  = fullfile(basedir,subjects(ns).name,'96dir_run1','fw_afq_ET_ACT_LiFE_3.0.2_lmax8');
    file5tt=fullfile(fwDir, 'dti96trilin/mrtrix/dwi_aligned_trilin_noMEC_5tt.mif');
    for nh=1:length(hemis); for nl=1:length(lmaxs)
        for nt=1:length(tractNames)
            if strcmp(tractNames{nt},'AllROIs')
                howManyFibers = '100000';
            else
                howManyFibers = '100';
            end
            
            dtiDir  = fullfile(fwDir ,'dti96trilin');
            t1Dir   = fullfile(fwDir ,'t1');
            roi1    = fullfile(t1Dir ,'niftiRois',[hemis{nh} '_' roi1s{nt}]);
            roi2    = fullfile(t1Dir ,'niftiRois',[hemis{nh} '_' roi2s{nt}]);
            wmMask  = fullfile(dtiDir ,'mrtrix','dwi_aligned_trilin_noMEC_wmMask_dilated.mif');
            fod     = fullfile(dtiDir,'mrtrix', ...
                      ['dwi_aligned_trilin_noMEC_csd_lmax' lmaxs{nl} '.mif']);
%             fod     = '/black/localhome/glerma/TESTDATA/AFQ/input/MareikeS13/dti96trilin/mrtrix/dwi_aligned_trilin_noMEC_wmCsd_autolmax.mif';
            tract   = fullfile(dtiDir,'mrtrix',[hemis{nh} ...
                                                '_' tractNames{nt} ...
                                                '_lmax' lmaxs{nl} ...
                                                '_select' howManyFibers ...
                                                '_iFOD1_ang13.5_cutoff0.1.tck']);
            
%                        '-mask ' wmMask ' ' ...

            cmd_str = ['tckgen -force -info ' ... 
                       '-algorithm  iFOD1 ' ...
                       '-backtrack -crop_at_gmwmi -info ' ...
                       '-act ' file5tt ' ' ...
                       '-select ' howManyFibers ' ' ...
                       '-seed_image ' roi1  ' ' ...
                       '-include ' roi2  ' ' ...
                       '-angle 13.5 ' ...
                       '-cutoff 0.1 ' ...
                       fod ' ' ...
                       tract];

            AFQ_mrtrix_cmd(cmd_str,0,1,3)
end;end;end;end